# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:z

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
